"""Data registry: a per-run audit record linking resolved configs to artifacts.

Each constructed dataset produces a registry entry (dataset, noise type/rate,
seed, counts, config hash). A global ``results/registry.json`` maps config_hash
-> entry so any reported number can be regenerated byte-identically.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from .. import config as config_mod
from ..utils import write_json_atomic


def build_registry_entry(cfg: dict[str, Any], bundle_meta: dict[str, Any]) -> dict[str, Any]:
    """Assemble a registry entry from the resolved config and bundle metadata."""
    return {
        "config_hash": config_mod.hash_config(cfg),
        "dataset": cfg["dataset"]["name"],
        "noise_type": cfg["noise"]["type"],
        "noise_rate": float(cfg["noise"]["rate"]),
        "noise_seed": int(cfg["noise"].get("seed", 0)),
        "seed": int(cfg.get("seed", 0)),
        "num_train": bundle_meta.get("num_train"),
        "num_noisy": bundle_meta.get("num_noisy"),
        "num_classes": bundle_meta.get("num_classes"),
        "val_frac": float(cfg["dataset"].get("val_frac", 0.1)),
        "config": cfg,
    }


def update_registry_index(registry_path: Path, entry: dict[str, Any]) -> None:
    """Merge ``entry`` into the global registry index keyed by config_hash."""
    if registry_path.exists():
        index = read_registry_index(registry_path)
    else:
        index = {}
    index[entry["config_hash"]] = entry
    write_json_atomic(registry_path, index)


def read_registry_index(registry_path: Path) -> dict[str, Any]:
    """Read the registry index; returns {} if absent."""
    if not registry_path.exists():
        return {}
    import json

    with open(registry_path, encoding="utf-8") as f:
        return json.load(f)
